apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: WholeTale
spec:
  selector:
    matchLabels:
      app: WholeTale
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: WholeTale
        tier: database
    spec:
      containers:
      - image: mongo:3.2
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo
          mountPath: /data
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo-volume-claim
