apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: WholeTale
spec:
  selector:
    matchLabels:
      app: WholeTale
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: WholeTale
        tier: backend
    spec:
      containers:
      - image: redis
        name: redis
