# Created with:
#   kubectl create secret generic registry-secret \
#     --from-file=registry/auth/registry.password \
#     --from-literal=username=fido \
#     --from-literal=password=secretpass
# Should probably generate this automatically and randomly
# 
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    app: WholeTale
type: Opaque
data:
  password: c2VjcmV0cGFzcw==
  registry.password: ZmlkbzokMnkkMDUkOTdaLnIzYXRSemtYZDFwQTh0bTRwT2pWMXJJa3NCSTRET3Y4UzV4SDBHc1d1ZjQ4TTJwQnEKCg==
  username: Zmlkbw==
