#!/bin/bash

apt-get update
apt-get -y install telnet mc
pip3 install pudb

mv /girder/girder/cli/serve.py /girder/girder/cli/serve-orig.py
cp /girder/girder/cli/serve-debug.py /girder/girder/cli/serve.py

girder serve