
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kubernetes-csi/drivers"
  version = "v1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.12.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.12.0"

[[override]]
  version = "kubernetes-1.12.0"
  name = "k8s.io/api"

[[override]]
  version = "kubernetes-1.12.0"
  name = "k8s.io/apiserver"

[[override]]
  version = "kubernetes-1.12.0"
  name = "k8s.io/apiextensions-apiserver"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.1.0"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[override]]
  name = "gopkg.in/square/go-jose.v2"
  version = "2.1.7"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
